/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DaysOfTheWeek */

#ifndef _Included_DaysOfTheWeek
#define _Included_DaysOfTheWeek
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DaysOfTheWeek
 * Method:    displayDays
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_DaysOfTheWeek_displayDays
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
