/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Reverse */

#ifndef _Included_Reverse
#define _Included_Reverse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Reverse
 * Method:    reverse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Reverse_reverse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
