/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Fibonacci */

#ifndef _Included_Fibonacci
#define _Included_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Fibonacci
 * Method:    returnFibo
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_Fibonacci_returnFibo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
