/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Factorial */

#ifndef _Included_Factorial
#define _Included_Factorial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Factorial
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Factorial_fact
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
